---
- name: Create VM
  hosts: localhost
  vars:
    - resource_group: B2C6D
    - ipadressname: TestIp
    - nicname: TestNIC
    - virtual_network: myVnet
    - subnet: mySubnet
    - security_group: secgroup001
    - vmname: {{ vm_name }}
    - vmsize: Standard_B1s
    - admin_username: {{ vm_name }}
    - public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKRTkgktS3nlLpaJMWqb/liYo4yiQLrfZqiJovCZCOz8qMHJexbPBNmU0IBcHCA7Dy3lq/viVEqMwZz7z6xUnfmJ/noxMNz6aXsNSwuub5N5LyRCDxMSKBMFulonmYff13FsQ8Wv4Mkd7J1t3wEVOXry4m0s5/ExcBBuySjGbcw5o9yxzGPvl3KtTq2TaQpW71gSSk8tqiPnnKpZrtlnk3DSDMkF0LK/erK1BbdAtCcR60sUgno7opElOSa1BXXXf3CDn/sidC2u6BwL2J52AXy3NIqxkP8ixWeYdfa7yJMRLONaV/RYkYiDJmqEITzhzN67Dt24rgiN8UbFoANUEB rsa-key-20230615
  tasks:
    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ ipadressname }}"
      register: public_ip_result

    - name: Display Ip result
      debug:
        msg: "{{ public_ip_result }}"

    - set_fact:
        public_ip_address: "{{ public_ip_result.state.ip_address }}"

    - name: Display IP address
      debug:
        var: public_ip_address

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nicname }}"
        virtual_network: "{{ virtual_network }}"
        subnet: "{{ subnet }}"
        public_ip_name: "{{ ipadressname }}"
        security_group: "{{ security_group }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vmname }}"
        vm_size: "{{ vmsize }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/{{ admin_username }}/.ssh/authorized_keys
            key_data: "{{ public_key }}"
        network_interfaces: "{{ nicname }}"
        image:
          offer: 0001-com-ubuntu-server-focal-daily
          publisher: Canonical
          sku: "20_04-daily-lts"
          version: latest

    - name: Add public IP to group
      add_host:
        name: "{{ public_ip_address }}"
        groups: ansible_hosts

    - name: Wait for SSH port
      wait_for:
        host: "{{ public_ip_address }}"
        port: 22
        delay: 10
        timeout: 180
      become: false

- name: Install Ansible on VM
  hosts: ansible_hosts
  remote_user: TestVM
  vars:
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no -i /home/AnsibleVM/ssh/TestVM_Private_Key.pem"
    - ansible_python_interpreter: /usr/bin/python3.8
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Update package lists
      command: apt update
      changed_when: false

    - name: Upgrade packages
      command: apt upgrade -y

    - name: Install Python 3 and pip
      apt:
        name:
          - python3
          - python3-dev
          - python3-setuptools
          - python3-apt
          - curl
          - python3-pip
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install Azure modules for Ansible
      pip:
        name:
          - "ansible[azure]"
        state: latest

    - name: Install setuptools-rust
      command: sudo pip3 install setuptools-rust

    - name: Upgrade pip
      command: sudo pip3 install --upgrade pip

    - name: Change directory to home
      ansible.builtin.shell:
        cmd: |
          cd /home/TestVM/
      become: false

    - name: Install Azure collection
      ansible.builtin.shell: ansible-galaxy collection install azure.azcollection --collections-path /home/TestVM/.ansible/collections

    - name: Change directory to azcollection
      ansible.builtin.shell:
        cmd: |
          cd ~/.ansible/collections/ansible_collections/azure/azcollection
      become: false

    - name: Install Azure collection dependencies
      ansible.builtin.shell:
        cmd: pip3 install -r /home/TestVM/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
      become: true

    - name: Upgrade pyOpenSSL
      become: true
      pip:
        name: pyopenssl
        state: latest

    - name: Create .azure directory
      file:
        path: /home/TestVM/.azure
        state: directory
        mode: "0700"
        owner: TestVM
        group: TestVM

    - name: Create Azure credentials file
      copy:
        content: |
          [default]
          subscription_id=8d9ee96d-4dfb-422e-880b-151705e0d558
          client_id=8cf2ed0e-9a0f-4fb5-aaa7-9514f4f8848a
          secret=q.x8Q~sidyz829EFLxZV1BjpI8W8ErYjkzB1nbGQ
          tenant=586e785a-8271-4fc6-a0c4-59fec8a68975
        dest: /home/TestVM/.azure/credentials
        mode: "0600"
        owner: TestVM
        group: TestVM

    - name: Create 'playbooks' directory
      file:
        path: /home/TestVM/playbooks
        state: directory
        mode: "0755"
        owner: TestVM
        group: TestVM
