name: .NET Core

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: devopsb2dspellenplatform    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.\bin\Debug\net6.0\publish' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use (sterf)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: install dependencies
        run: |
         cd ./Pfff/Pfff
         dotnet restore 
         
      - name: build project
        run: |
         cd ./Pfff/Pfff
         dotnet build --configuration Release --no-restore
      
      - name: publish project
        run: |
         cd ./Pfff/Pfff
         dotnet publish -c Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
     - uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     
    # Deploy to Azure Web apps
     - name: 'Run Azure webapp deploy action using Azure Credentials'
       uses: azure/webapps-deploy@v2
       with: 
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
       
     - name: logout
       run: |
         az logout
