name: .NET Core

on: [push]

env:
  AZURE_WEBAPP_NAME: Pfff.sln    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'Pfff'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
        run: nuget restore

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Run msbuild
        run: msbuild .\Pfff.sln

          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using Azure Credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: Pfff.sln # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Pfff'
      
      - name: logout
        run: |
          az logout
