name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: DevOpsB2DSpellenPlatform
    - name: Build
      run: dotnet build --no-restore
      working-directory: DevOpsB2DSpellenPlatform
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: DevOpsB2DSpellenPlatform
    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: DevOpsB2DSpellenPlatform
        path: DevOpsB2DSpellenPlatform
      #
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: devopsb2dspellenplatform.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: DevOpsB2DSpellenPlatform
          path: DevOpsB2DSpellenPlatform

      - name: Deploy
        id: login
        uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: DevOpsB2DSpellenPlatform 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: DevOpsB2DSpellenPlatform
